// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7EaFzu_wFUqSWdOBE8RVqQWLW79enjfA',
    appId: '1:900694066206:android:1b17ab579f20d72bb39a0f',
    messagingSenderId: '900694066206',
    projectId: 'notification-fc948',
    storageBucket: 'notification-fc948.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqjV6ZhY-WAuy2kAi2JApQ2OP8rG_Jl3E',
    appId: '1:900694066206:ios:8a35a6bc5c2f0342b39a0f',
    messagingSenderId: '900694066206',
    projectId: 'notification-fc948',
    storageBucket: 'notification-fc948.appspot.com',
    iosBundleId: 'com.notification.myNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkcfkZ-3YiR9uB7p-YFOA7MyJJ4wkF5V4',
    appId: '1:900694066206:web:f6b86860f0d04489b39a0f',
    messagingSenderId: '900694066206',
    projectId: 'notification-fc948',
    authDomain: 'notification-fc948.firebaseapp.com',
    storageBucket: 'notification-fc948.appspot.com',
    measurementId: 'G-LF8DVDN4HL',
  );
}
